server.port=8080
app.name=Steam player Profile API
app.dev.name=Fatima
app.dev.intro= Java Developer, API builder, and sometimes gamer
app.dev.theme= Gaming
app.dev.favGame= Elden Ring
app.dev.learning= Spring Boot Rest API